# Generated by Django 5.2 on 2026-04-20 07:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_lat_alter_place_lng_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='places_plac_order_66e296_idx'),
        ),
    ]
